// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingSimulator_Backend.Data;

#nullable disable

namespace TradingSimulator_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014220941_AddFriendsRelation")]
    partial class AddFriendsRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StockHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockHistory");
                });

            modelBuilder.Entity("TradingSimulator_Backend.Models.Friends", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId1")
                        .IsUnique();

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("TradingSimulator_Backend.Models.StockLogoName", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.ToTable("StockLogoName");
                });

            modelBuilder.Entity("TradingSimulator_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvestedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfitLoss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserObj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FriendsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FriendsId1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FriendsId2")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ProfitLoss")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FriendsId");

                    b.HasIndex("FriendsId1");

                    b.HasIndex("FriendsId2");

                    b.ToTable("UserObj");
                });

            modelBuilder.Entity("Portfolio", b =>
                {
                    b.HasOne("TradingSimulator_Backend.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Portfolio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stock", b =>
                {
                    b.HasOne("Portfolio", "Portfolio")
                        .WithMany("Stocks")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("StockHistory", b =>
                {
                    b.HasOne("Stock", "Stock")
                        .WithMany("History")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("TradingSimulator_Backend.Models.Friends", b =>
                {
                    b.HasOne("TradingSimulator_Backend.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("TradingSimulator_Backend.Models.Friends", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingSimulator_Backend.Models.User", null)
                        .WithOne("Friends")
                        .HasForeignKey("TradingSimulator_Backend.Models.Friends", "UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserObj", b =>
                {
                    b.HasOne("TradingSimulator_Backend.Models.Friends", null)
                        .WithMany("FriendsList")
                        .HasForeignKey("FriendsId");

                    b.HasOne("TradingSimulator_Backend.Models.Friends", null)
                        .WithMany("ReceivedRequests")
                        .HasForeignKey("FriendsId1");

                    b.HasOne("TradingSimulator_Backend.Models.Friends", null)
                        .WithMany("SentRequests")
                        .HasForeignKey("FriendsId2");
                });

            modelBuilder.Entity("Portfolio", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Stock", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("TradingSimulator_Backend.Models.Friends", b =>
                {
                    b.Navigation("FriendsList");

                    b.Navigation("ReceivedRequests");

                    b.Navigation("SentRequests");
                });

            modelBuilder.Entity("TradingSimulator_Backend.Models.User", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
